/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SakutaroPoemFactory } from "./SakutaroPoemFactory";
export type { SakutaroPoem } from "./SakutaroPoem";
